package com.seu.android_diabetes.vo;

import java.util.Date;



public class PIVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.vascular_aging_degree
     *
     * @mbg.generated
     */
    private Integer vascularAgingDegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.exercise_amount
     *
     * @mbg.generated
     */
    private Float exerciseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.fasting_blood_glucose
     *
     * @mbg.generated
     */
    private Float fastingBloodGlucose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.postprandial_blood_glucose
     *
     * @mbg.generated
     */
    private Float postprandialBloodGlucose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.prescription_id
     *
     * @mbg.generated
     */
    private Integer prescriptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.id
     *
     * @return the value of indicator.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.id
     *
     * @param id the value for indicator.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.user_id
     *
     * @return the value of indicator.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.user_id
     *
     * @param userId the value for indicator.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.age
     *
     * @return the value of indicator.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.age
     *
     * @param age the value for indicator.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.sex
     *
     * @return the value of indicator.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.sex
     *
     * @param sex the value for indicator.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.vascular_aging_degree
     *
     * @return the value of indicator.vascular_aging_degree
     *
     * @mbg.generated
     */
    public Integer getVascularAgingDegree() {
        return vascularAgingDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.vascular_aging_degree
     *
     * @param vascularAgingDegree the value for indicator.vascular_aging_degree
     *
     * @mbg.generated
     */
    public void setVascularAgingDegree(Integer vascularAgingDegree) {
        this.vascularAgingDegree = vascularAgingDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.exercise_amount
     *
     * @return the value of indicator.exercise_amount
     *
     * @mbg.generated
     */
    public Float getExerciseAmount() {
        return exerciseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.exercise_amount
     *
     * @param exerciseAmount the value for indicator.exercise_amount
     *
     * @mbg.generated
     */
    public void setExerciseAmount(Float exerciseAmount) {
        this.exerciseAmount = exerciseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.fasting_blood_glucose
     *
     * @return the value of indicator.fasting_blood_glucose
     *
     * @mbg.generated
     */
    public Float getFastingBloodGlucose() {
        return fastingBloodGlucose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.fasting_blood_glucose
     *
     * @param fastingBloodGlucose the value for indicator.fasting_blood_glucose
     *
     * @mbg.generated
     */
    public void setFastingBloodGlucose(Float fastingBloodGlucose) {
        this.fastingBloodGlucose = fastingBloodGlucose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.postprandial_blood_glucose
     *
     * @return the value of indicator.postprandial_blood_glucose
     *
     * @mbg.generated
     */
    public Float getPostprandialBloodGlucose() {
        return postprandialBloodGlucose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.postprandial_blood_glucose
     *
     * @param postprandialBloodGlucose the value for indicator.postprandial_blood_glucose
     *
     * @mbg.generated
     */
    public void setPostprandialBloodGlucose(Float postprandialBloodGlucose) {
        this.postprandialBloodGlucose = postprandialBloodGlucose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.prescription_id
     *
     * @return the value of indicator.prescription_id
     *
     * @mbg.generated
     */
    public Integer getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.prescription_id
     *
     * @param prescriptionId the value for indicator.prescription_id
     *
     * @mbg.generated
     */
    public void setPrescriptionId(Integer prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.create_time
     *
     * @return the value of indicator.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.create_time
     *
     * @param createTime the value for indicator.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}