package com.seu.android_diabetes.vo;

import java.util.Date;

public class Prescription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.patient_id
     *
     * @mbg.generated
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.therapist_id
     *
     * @mbg.generated
     */
    private Integer therapistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.video_url
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_prescription.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.id
     *
     * @return the value of exercise_prescription.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.id
     *
     * @param id the value for exercise_prescription.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.patient_id
     *
     * @return the value of exercise_prescription.patient_id
     *
     * @mbg.generated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.patient_id
     *
     * @param patientId the value for exercise_prescription.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.therapist_id
     *
     * @return the value of exercise_prescription.therapist_id
     *
     * @mbg.generated
     */
    public Integer getTherapistId() {
        return therapistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.therapist_id
     *
     * @param therapistId the value for exercise_prescription.therapist_id
     *
     * @mbg.generated
     */
    public void setTherapistId(Integer therapistId) {
        this.therapistId = therapistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.doctor_id
     *
     * @return the value of exercise_prescription.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.doctor_id
     *
     * @param doctorId the value for exercise_prescription.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.name
     *
     * @return the value of exercise_prescription.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.name
     *
     * @param name the value for exercise_prescription.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.video_url
     *
     * @return the value of exercise_prescription.video_url
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.video_url
     *
     * @param videoUrl the value for exercise_prescription.video_url
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.note
     *
     * @return the value of exercise_prescription.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.note
     *
     * @param note the value for exercise_prescription.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.status
     *
     * @return the value of exercise_prescription.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.status
     *
     * @param status the value for exercise_prescription.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.create_time
     *
     * @return the value of exercise_prescription.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.create_time
     *
     * @param createTime the value for exercise_prescription.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_prescription.update_time
     *
     * @return the value of exercise_prescription.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_prescription.update_time
     *
     * @param updateTime the value for exercise_prescription.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}